### ISSUE TITLE
Document in Faq how to jump to first message in chat

### ISSUE THREAD

**Issue by csb0730** [deltachat/deltachat-pages#69] opened 2018-04-07 10:28 UTC
This is the procedure:

To go to the first messag you can:

    select "search" from the menu
    do not enter a search term
    click on the up arrow beside the search field

(maybe we shoud document this somewhere in the faq) (@r10s) :-)

**Comment by testbird** [comment] 2019-03-28 15:18
The workaround does not seem to work anymore.

The problem is still there (missing button, or better some slider-handle on the side to scrol the whole chat in one swipe).

**Comment by r10s** [comment] 2019-03-28 15:43
the feature-proposal as such can be discussed in the forum then.
closing this as there is no actionable item for the pages.

**Closed as completed by r10s** 2019-03-28 15:43 UTC

**Comment by csb0730** [comment] 2019-03-28 20:08
The procedure above only worked until v0.20.0 with telegram UI.
So for new version's it's not valid any more.

**Comment by csb0730** [comment] 2019-03-28 20:10
Hi Björn,

as there is no solution for this any more there should be a new issue
about it.

In practice this is a problem (at least for me ;-) )

Is there a possible solution for that problem at horizon?

VG


Am 28.03.19 um 16:43 schrieb björn petersen:

**Comment by r10s** [comment] 2019-03-28 20:53
not sure if there is an issue. feel free to add a feature-request to the forum. as it is not totally clear how such a control could look like and if there is a real need, it can be discussed there first.

it is planned to add more media-tabs to the chat-profile, see https://github.com/deltachat/deltachat-android/issues/428 , and it will probably also be possible to go eg. from an image/link/document to the corresponding position in the chat. 
this might also make this "go to the last post" feature less important. i personally would prefer to put some effort to this :)

**Comment by testbird** [comment] 2019-03-29 16:15
Isn't there some (auto-appearing?) scrollbar slider in the gui widgets that simply allows to "grab a handle and slide the entire list up and down" in one go. I think I've even seen one somewhere popping up the index position (A,B,C,.. or date) when sliding.

**Comment by r10s** [comment] 2019-03-29 17:10
this is available for the contacts
